---
# Azure AKS cluster resource configuration
apiVersion: compute.azure.crossplane.io/v1alpha1
kind: AKSCluster
metadata:
  name: demo-cluster
spec:
  providerRef:
    name: azure-provider
  connectionSecretRef:
    name: aks-demo-cluster-connection
  reclaimPolicy: Delete
  resourceGroupName: group-westus-1
  location: West US 2
  version: 1.12.5
  nodeCount: 1
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: false